import { test, expect } from '@playwright/test';

test('organization to project, task, discussion, AI state and logout', async ({ page }, testInfo) => {
  const failures: string[] = [];
  page.on('pageerror', e => failures.push(e.message));
  await page.goto('/');
  await page.getByLabel('Your name', { exact: true }).fill('Alex Morgan');
  await page.getByLabel('Email address', { exact: true }).fill(`alex-${Date.now()}@example.com`);
  await page.getByRole('button', { name: 'Enter workspace' }).click();
  await page.getByRole('button', { name: 'Create your organization' }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Studio '+Date.now());
  await page.getByRole('button', { name: 'Create organization', exact: true }).click();
  await page.getByRole('button', { name: 'New project', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Platform launch');
  await page.getByLabel('Description', { exact: true }).fill('A thoughtful home for our next release.');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Platform launch', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'New task', exact: true }).click();
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Verify tenant isolation');
  await page.getByLabel('Description', { exact: true }).fill('Run the security tests before release.');
  await page.getByRole('button', { name: 'Create task', exact: true }).click();
  await page.getByRole('button', { name: /Verify tenant isolation/ }).click();
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('in_progress');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('region', { name: 'In progress', exact: true })).toContainText('Verify tenant isolation');
  await page.screenshot({ path: `../output/playwright/devhub-${testInfo.project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: 'Discussions', exact: true }).click();
  await page.getByRole('button', { name: 'New discussion', exact: true }).click();
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Launch readiness');
  await page.getByLabel('Your message', { exact: true }).fill('Which checks should we run?');
  await page.getByRole('button', { name: 'Post discussion', exact: true }).click();
  await page.getByLabel('Add a reply', { exact: true }).fill('Start with the permissions matrix.');
  await page.getByRole('button', { name: 'Post reply', exact: true }).click();
  await expect(page.getByText('Start with the permissions matrix.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'AI assistant', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Generate a draft' })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome to DevHub' })).toBeVisible();
  expect(failures).toEqual([]);
});
